services:
  - type: web
    name: criptoalertbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "YOUR_BOT_TOKEN_HERE"
      - key: TELEGRAM_CHAT_ID
        value: "YOUR_CHAT_ID_HERE"
    autoDeploy: false
    healthCheckPath: /
    envVarsDiff: false
